version: "3"
services:
  app:
    image: oflow:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/work:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: 1000:1000
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
